(()=>{"use strict";const m="piano-dev-v1",L=["manifest","json"].join("."),f=()=>{try{const n=JSON.parse(localStorage.getItem(m)||"null");return n&&n.on===!0?n:null}catch{return null}};window.PianoDev={settings:()=>f()||{}},window.createPianoDevMode=n=>{let a=f(),y=[];const d=e=>{a=e;try{e?localStorage.setItem(m,JSON.stringify(e)):localStorage.removeItem(m)}catch{}},l=new URLSearchParams(location.search);if(l.has("dev")){d(l.get("dev")==="0"?null:{...a||{},on:!0}),l.delete("dev");try{history.replaceState(null,"",location.pathname+(l.size?"?"+l:"")+location.hash)}catch{}}const c=document.createElement("button");c.type="button",c.className="sidebar-dev",c.hidden=!0,c.innerHTML='<span aria-hidden="true">⚙</span> Nhà phát triển',(document.querySelector(".sidebar-feedback")||document.querySelector(".primary-nav"))?.after(c);const o=document.createElement("dialog");o.className="dev-dialog",o.setAttribute("aria-labelledby","dev-title"),o.innerHTML=`<form method="dialog">
      <h2 id="dev-title">Chế độ nhà phát triển</h2>
      <p>Chỉ áp dụng cho trình duyệt này. Không có trên giao diện cho tới khi được bật.</p>
      <label class="dev-row"><input type="checkbox" id="dev-unlock"> Mở toàn bộ lộ trình (bài hiện tại giữ nguyên)</label>
      <section class="dev-section"><h3>Piano in 162 · Ivy Audio</h3>
        <p>Chọn thư mục <code>assets/piano162-web</code> trên máy bạn (tạo bằng <code>scripts/build-piano162-web.py</code>). Các file chỉ được đọc trong trình duyệt này, trong phiên này; không tải lên và không có trong bản công khai.</p>
        <button type="button" id="dev-piano162">Chọn thư mục piano162-web…</button>
        <input type="file" id="dev-piano162-files" webkitdirectory multiple hidden>
        <p id="dev-piano162-status" class="dev-status" role="status"></p></section>
      <div class="dev-actions"><button type="button" id="dev-off">Tắt chế độ nhà phát triển</button><button value="close">Đóng</button></div>
    </form>`,document.body.append(o);const i=e=>o.querySelector("#"+e),v=()=>{c.hidden=!a,i("dev-unlock").checked=a?.unlockAll===!0};let h=[];return document.querySelector(".brand")?.addEventListener("click",()=>{const e=Date.now();h=[...h.filter(u=>e-u<3e3),e],h.length>=7&&(h=[],d({...a||{},on:!0}),v(),o.showModal?.())}),c.addEventListener("click",()=>o.showModal?.()),i("dev-unlock").addEventListener("change",()=>{d({...a,unlockAll:i("dev-unlock").checked}),n.refreshPath()}),i("dev-off").addEventListener("click",()=>{d(null),v(),o.close?.(),n.refreshPath()}),i("dev-piano162").addEventListener("click",()=>i("dev-piano162-files").click()),i("dev-piano162-files").addEventListener("change",async e=>{const u=[...e.target.files];e.target.value="";const g=i("dev-piano162-status"),b=new Map(u.map(t=>[t.name,t])),k=b.get(L);if(!k){g.textContent="Không thấy manifest.json: hãy chọn đúng thư mục piano162-web.";return}let p;try{p=JSON.parse(await k.text())}catch{g.textContent="manifest.json không đọc được.";return}const s=[...Object.values(p.files||{}),...Object.values(p.release?.files||{})],r=s.filter(t=>!b.has(t));if(!s.length||r.length>s.length/2){g.textContent=`Thư mục thiếu ${r.length}/${s.length} file mẫu.`;return}for(const t of y)URL.revokeObjectURL(t);const w=new Map([...b].map(([t,S])=>[t,URL.createObjectURL(S)]));y=[...w.values()],n.addPiano162(w,p.instrument||"Piano in 162"),g.textContent=`Đã nạp ${s.length-r.length}/${s.length} file mẫu. Bộ đàn đã chuyển sang “Piano in 162 · máy bạn” (Âm thanh); mở một bài và bấm Nghe mẫu.`+(r.length?` Thiếu ${r.length} file.`:"")}),v(),{settings:()=>a||{}}}})();
