(()=>{"use strict";const p="piano-dev-v1",L=["manifest","json"].join("."),f=()=>{try{const n=JSON.parse(localStorage.getItem(p)||"null");return n&&n.on===!0?n:null}catch{return null}};window.PianoDev={settings:()=>f()||{}},window.createPianoDevMode=n=>{let a=f(),y=[];const r=e=>{a=e;try{e?localStorage.setItem(p,JSON.stringify(e)):localStorage.removeItem(p)}catch{}},l=new URLSearchParams(location.search);if(l.has("dev")){r(l.get("dev")==="0"?null:{...a||{},on:!0}),l.delete("dev");try{history.replaceState(null,"",location.pathname+(l.size?"?"+l:"")+location.hash)}catch{}}const c=document.createElement("button");c.type="button",c.className="sidebar-dev",c.hidden=!0,c.innerHTML='<span aria-hidden="true">⚙</span> Nhà phát triển',(document.querySelector(".sidebar-feedback")||document.querySelector(".primary-nav"))?.after(c);const i=document.createElement("dialog");i.className="dev-dialog",i.setAttribute("aria-labelledby","dev-title"),i.innerHTML=`<form method="dialog">
      <h2 id="dev-title">Chế độ nhà phát triển</h2>
      <p>Chỉ áp dụng cho trình duyệt này. Không có trên giao diện cho tới khi được bật.</p>
      <label class="dev-row"><input type="checkbox" id="dev-unlock"> Mở toàn bộ lộ trình (bài hiện tại giữ nguyên)</label>
      <label class="dev-row"><input type="checkbox" id="dev-rewards"> Mở khóa toàn bộ phần thưởng: vật phẩm và danh hiệu (nốt vàng và đồ đã mua thật không đổi)</label>
      <section class="dev-section"><h3>Piano in 162 · Ivy Audio</h3>
        <p>Chọn thư mục <code>assets/piano162-web</code> trên máy bạn (tạo bằng <code>scripts/build-piano162-web.py</code>). Các file chỉ được đọc trong trình duyệt này, trong phiên này; không tải lên và không có trong bản công khai.</p>
        <button type="button" id="dev-piano162">Chọn thư mục piano162-web…</button>
        <input type="file" id="dev-piano162-files" webkitdirectory multiple hidden>
        <p id="dev-piano162-status" class="dev-status" role="status"></p></section>
      <div class="dev-actions"><button type="button" id="dev-off">Tắt chế độ nhà phát triển</button><button value="close">Đóng</button></div>
    </form>`,document.body.append(i);const t=e=>i.querySelector("#"+e),m=()=>{c.hidden=!a,t("dev-unlock").checked=a?.unlockAll===!0,t("dev-rewards").checked=a?.unlockRewards===!0};let h=[];return document.querySelector(".brand")?.addEventListener("click",()=>{const e=Date.now();h=[...h.filter(u=>e-u<3e3),e],h.length>=7&&(h=[],r({...a||{},on:!0}),m(),i.showModal?.())}),c.addEventListener("click",()=>i.showModal?.()),t("dev-unlock").addEventListener("change",()=>{r({...a,unlockAll:t("dev-unlock").checked}),n.refreshPath()}),t("dev-rewards").addEventListener("change",()=>{r({...a,unlockRewards:t("dev-rewards").checked}),n.refreshRewards?.()}),t("dev-off").addEventListener("click",()=>{r(null),m(),i.close?.(),n.refreshPath(),n.refreshRewards?.()}),t("dev-piano162").addEventListener("click",()=>t("dev-piano162-files").click()),t("dev-piano162-files").addEventListener("change",async e=>{const u=[...e.target.files];e.target.value="";const v=t("dev-piano162-status"),b=new Map(u.map(o=>[o.name,o])),k=b.get(L);if(!k){v.textContent="Không thấy manifest.json: hãy chọn đúng thư mục piano162-web.";return}let g;try{g=JSON.parse(await k.text())}catch{v.textContent="manifest.json không đọc được.";return}const s=[...Object.values(g.files||{}),...Object.values(g.release?.files||{})],d=s.filter(o=>!b.has(o));if(!s.length||d.length>s.length/2){v.textContent=`Thư mục thiếu ${d.length}/${s.length} file mẫu.`;return}for(const o of y)URL.revokeObjectURL(o);const w=new Map([...b].map(([o,S])=>[o,URL.createObjectURL(S)]));y=[...w.values()],n.addPiano162(w,g.instrument||"Piano in 162"),v.textContent=`Đã nạp ${s.length-d.length}/${s.length} file mẫu. Bộ đàn đã chuyển sang “Piano in 162 · máy bạn” (Âm thanh); mở một bài và bấm Nghe mẫu.`+(d.length?` Thiếu ${d.length} file.`:"")}),m(),{settings:()=>a||{}}}})();
