(()=>{"use strict";const g="piano-dev-v1",P=["manifest","json"].join("."),y=()=>{try{const n=JSON.parse(localStorage.getItem(g)||"null");return n&&n.on===!0?n:null}catch{return null}};window.PianoDev={settings:()=>y()||{}},window.createPianoDevMode=n=>{let o=y(),u=[];const d=t=>{o=t;try{t?localStorage.setItem(g,JSON.stringify(t)):localStorage.removeItem(g)}catch{}},l=new URLSearchParams(location.search);if(l.has("dev")){d(l.get("dev")==="0"?null:{...o||{},on:!0}),l.delete("dev");try{history.replaceState(null,"",location.pathname+(l.size?"?"+l:"")+location.hash)}catch{}}const c=document.createElement("button");c.type="button",c.className="sidebar-dev",c.hidden=!0,c.innerHTML='<span aria-hidden="true">⚙</span> Nhà phát triển',(document.querySelector(".sidebar-feedback")||document.querySelector(".primary-nav"))?.after(c);const i=document.createElement("dialog");i.className="dev-dialog",i.setAttribute("aria-labelledby","dev-title"),i.innerHTML=`<form method="dialog">
      <h2 id="dev-title">Chế độ nhà phát triển</h2>
      <p>Chỉ áp dụng cho trình duyệt này. Không có trên giao diện cho tới khi được bật.</p>
      <label class="dev-row"><input type="checkbox" id="dev-unlock"> Mở toàn bộ lộ trình (bài hiện tại giữ nguyên)</label>
      <label class="dev-row"><input type="checkbox" id="dev-rewards"> Mở khóa toàn bộ phần thưởng: vật phẩm và danh hiệu (nốt vàng và đồ đã mua thật không đổi)</label>
      <section class="dev-section"><h3>Piano in 162 · Ivy Audio</h3>
        <p>Chọn thư mục <code>assets/piano162-web</code> trên máy bạn (tạo bằng <code>scripts/build-piano162-web.py</code>). Các file chỉ được đọc trong trình duyệt này, trong phiên này; không tải lên và không có trong bản công khai.</p>
        <button type="button" id="dev-piano162">Chọn thư mục piano162-web…</button> <button type="button" id="dev-piano162-remove" hidden>Thôi dùng Piano in 162</button>
        <input type="file" id="dev-piano162-files" webkitdirectory multiple hidden>
        <p id="dev-piano162-status" class="dev-status" role="status"></p></section>
      <div class="dev-actions"><button type="button" id="dev-off">Tắt chế độ nhà phát triển</button><button value="close">Đóng</button></div>
    </form>`,document.body.append(i);const e=t=>i.querySelector("#"+t),b=()=>{c.hidden=!o,e("dev-unlock").checked=o?.unlockAll===!0,e("dev-rewards").checked=o?.unlockRewards===!0};let v=[];document.querySelector(".brand")?.addEventListener("click",()=>{const t=Date.now();v=[...v.filter(s=>t-s<3e3),t],v.length>=7&&(v=[],d({...o||{},on:!0}),b(),i.showModal?.())}),c.addEventListener("click",()=>i.showModal?.()),e("dev-unlock").addEventListener("change",()=>{d({...o,unlockAll:e("dev-unlock").checked}),n.refreshPath()}),e("dev-rewards").addEventListener("change",()=>{d({...o,unlockRewards:e("dev-rewards").checked}),n.refreshRewards?.()});const k=()=>{const t=n.removePiano162?.();for(const s of u)URL.revokeObjectURL(s);u=[],e("dev-piano162-remove").hidden=!0,t&&(e("dev-piano162-status").textContent="Đã thôi dùng Piano in 162; bộ đàn trở lại mặc định.")};return e("dev-piano162-remove").addEventListener("click",k),e("dev-off").addEventListener("click",()=>{k(),d(null),b(),i.close?.(),n.refreshPath(),n.refreshRewards?.()}),e("dev-piano162").addEventListener("click",()=>e("dev-piano162-files").click()),e("dev-piano162-files").addEventListener("change",async t=>{const s=[...t.target.files];t.target.value="";const m=e("dev-piano162-status"),f=new Map(s.map(a=>[a.name,a])),w=f.get(P);if(!w){m.textContent="Không thấy manifest.json: hãy chọn đúng thư mục piano162-web.";return}let p;try{p=JSON.parse(await w.text())}catch{m.textContent="manifest.json không đọc được.";return}const r=[...Object.values(p.files||{}),...Object.values(p.release?.files||{})],h=r.filter(a=>!f.has(a));if(!r.length||h.length>r.length/2){m.textContent=`Thư mục thiếu ${h.length}/${r.length} file mẫu.`;return}for(const a of u)URL.revokeObjectURL(a);const L=new Map([...f].map(([a,S])=>[a,URL.createObjectURL(S)]));u=[...L.values()],n.addPiano162(L,p.instrument||"Piano in 162"),e("dev-piano162-remove").hidden=!1,m.textContent=`Đã nạp ${r.length-h.length}/${r.length} file mẫu. Bộ đàn đã chuyển sang “Piano in 162 · máy bạn” (Âm thanh); mở một bài và bấm Nghe mẫu.`+(h.length?` Thiếu ${h.length} file.`:"")}),b(),{settings:()=>o||{}}}})();
