(()=>{"use strict";const r=[["foundation","Phím & đọc nhạc","◎"],["hands","Hai tay độc lập","⇄"],["rhythm","Nhịp & tiết tấu","♩"],["harmony","Gam & hòa âm","♬"],["accompaniment","Mẫu đệm","≋"],["music","Chơi thành âm nhạc","♫"]],s=[["keyboard","Tìm phím & quãng tám","foundation",[],[51],"Nhận phím bằng nhóm đen và phân biệt cùng tên ở các quãng tám."],["pulse","Giữ phách bên trong","foundation",[],[52,86],"Đếm đều khi đánh, giữ tiếng hoặc nghỉ; tốc độ phách không đổi."],["durations","Giữ đủ trường độ","foundation",["pulse"],[52],"Phân biệt tròn, trắng, đen; tiếp tục đếm khi không đánh thêm."],["rests","Khoảng nghỉ có nhịp","foundation",["pulse"],[53],"Giữ đúng khoảng lặng và vào nốt sau nghỉ đúng giờ."],["read-rh","Đọc khóa Sol","foundation",["keyboard"],[58,59],"Dùng nốt mốc, hướng đi và quãng để đọc tay phải."],["read-lh","Đọc khóa Fa","foundation",["keyboard"],[58,60],"Đọc tay trái bằng nốt mốc riêng, không đoán theo hình tay phải."],["fingers","Thế năm ngón","foundation",["keyboard"],[56,57],"Giữ thế tay thoải mái, các ngón xuống phím đều."],["intervals","Đọc & nghe quãng","foundation",["read-rh","read-lh"],[96,97,100],"Nhận bước, nhảy và khoảng cách; đặt hai nốt cùng một lần đánh."],["together","Hai tay cùng vào","hands",["pulse","fingers"],[1,133],"Hai tay gặp đúng thời điểm, không tách thành hai tiếng."],["hold","Một tay giữ, một tay đi","hands",["together","durations"],[4,61],"Giữ đủ nốt nền khi tay kia đổi nốt; không nhả hoặc đánh theo."],["alternate","Chuyền lượt & đổi vai","hands",["together","rests"],[3,64],"Một tay thực sự nghỉ; chuyển vai mà nhịp vẫn tiếp tục."],["ratio","Hai tốc độ trên một phách","hands",["together","durations"],[6,7],"Giữ điểm hẹn chung trong mẫu 2:1 và 1:2."],["opposite","Cùng & ngược hướng","hands",["together"],[2,22],"Giữ đường đi riêng của mỗi tay và gặp đúng vạch nhịp."],["canon","Hai câu vào lệch nhau","hands",["alternate","ratio"],[28,31],"Tay sau nhắc câu trong khi tay dẫn vẫn tiếp tục."],["eighths","Chia phách làm hai","rhythm",["pulse"],[8,146],"Đếm số và “và”; hai phần bằng nhau mà BPM không tăng."],["dotted","Dài–ngắn & dấu nối","rhythm",["eighths","durations"],[54,165],"Giữ tỉ lệ chấm dôi và giữ tiếng qua dấu nối, không đánh lại."],["syncopation","Vào giữa phách","rhythm",["eighths","rests"],[10,150],"Vào phần yếu hoặc giữ qua phách mạnh; nền vẫn đều."],["triple","Nhịp ba 3/4","rhythm",["pulse","durations"],[55],"Đếm ba phách mỗi ô, không thêm phách thứ tư."],["compound","Hai nhóm ba 6/8","rhythm",["eighths","triple"],[106],"Cảm nhận hai nhịp lớn, mỗi nhịp chia ba; khác ba phách của 3/4."],["triplets","Ba nốt trong một phách","rhythm",["eighths"],[42],"Chia ba đều trong cùng một phách."],["sixteenths","Bốn nốt trong một phách","rhythm",["eighths"],[108],"Đếm 1–e–và–a; đổi nhóm mà không đổi phách."],["polyrhythm","Ba đối hai","rhythm",["ratio","triplets"],[26,44],"Hai tay chia phách khác nhau nhưng cùng điểm bắt đầu và kết thúc."],["swing","Swing & shuffle","rhythm",["eighths"],[36,37],"Nghe dài–ngắn 2:1 trên phách đều; không chia đôi như móc đơn thẳng."],["thumb","Luồn & bắt chéo ngón","harmony",["fingers","read-rh"],[67,68,89],"Chuẩn bị ngón cái và nối đường gam qua điểm đổi ngón."],["shift","Mở rộng & dịch thế","harmony",["fingers","rests"],[87,88,90],"Chuẩn bị vị trí mới rồi trở về hoặc chuyển thế đúng nhịp."],["accidentals","Dấu hóa & hóa biểu","harmony",["read-rh","read-lh"],[66],"Phân biệt dấu hóa trong ô với hóa biểu áp dụng trên các quãng tám."],["major","Gam trưởng hai tay","harmony",["thumb","accidentals","opposite"],[21,91,93],"Giữ hóa biểu và hai đường ngón khác nhau khi chơi gam."],["minor","Màu giọng thứ","harmony",["accidentals"],[71,101],"Phân biệt thứ tự nhiên và hòa âm, nghe nốt thay đổi màu."],["chords","Hợp âm thành một tiếng","harmony",["fingers","durations"],[72,131,132],"Đặt sẵn các ngón và thả nhiều nốt cùng lúc."],["inversions","Thế đảo hợp âm","harmony",["chords"],[74,137],"Nhận thể gốc và hai đảo; chuyển cả hình tay thoải mái."],["voice-leading","Đổi hợp âm bằng đường gần","harmony",["inversions"],[75,135,138],"Tìm nốt chung, đổi thế gần và giữ nhịp khi chuyển vòng."],["seventh","Hợp âm bảy & trở về","harmony",["voice-leading","accidentals"],[116,153],"Đọc đúng nốt bảy, nghe dẫn bè về hợp âm chủ."],["sus","Nốt treo & giải quyết","harmony",["chords","intervals"],[118],"Nghe nốt treo trở về nốt ba, giữ các nốt còn lại."],["broken","Hợp âm rải đều","accompaniment",["chords","ratio"],[139,140],"Các nốt rải đều, ngón cái không to vọt, tay kia giữ câu."],["bass-chord","Bass & hợp âm đáp","accompaniment",["chords","alternate"],[17,147],"Giữ đường bass và đặt hợp âm đúng lượt."],["alberti","Thấp–cao–giữa–cao","accompaniment",["broken"],[24,149],"Đệm Alberti đều và nhẹ dưới giai điệu dài."],["touch","Liền, ngắt & điểm nhấn","music",["durations","together"],[11,12,82],"Hai tay dùng cách chạm khác nhau mà tempo không đổi."],["balance","Giai điệu nổi, nền nhẹ","music",["hold"],[13,151,152],"Nghe được người hát ở mỗi tay; nền nhẹ và đều."],["pedal","Tay trước, chân sau","music",["chords","durations"],[83,124],"Đổi pedal sau khi đánh hợp âm mới, tự nghe tiếng chồng/hở."],["phrases","Nối câu & chơi trọn","music",["hold","balance"],[65,154],"Luyện qua ranh giới ô/câu rồi nối bài, không chỉ lặp phần đầu."],["ear","Nghe, hát & tìm lại","music",["keyboard"],[71,100],"Nghe hoặc hát trước, rồi tìm phím để kiểm tra."],["reading","Đọc mới một lượt","music",["read-rh","read-lh","rests"],[85,128,129],"Quan sát trước rồi chơi một lượt chưa nghe mẫu; ghi chỗ vấp."],["create","Tạo câu trên nền đệm","music",["rests","balance"],[46,130],"Chọn cao độ và tiết tấu; giữ nền khi đổi câu của mình."]],o=`
1 together | pulse,fingers
2 opposite | together
3 alternate | rests
4 hold | durations
5 hold,alternate | together
6 ratio | durations
7 ratio | durations
8 eighths,ratio | together
9 eighths,ratio | hold
10 syncopation | hold
11 touch | together
12 touch | together
13 balance | together
14 balance,alternate | together
15 touch | together
16 hold,chords | balance
17 bass-chord | balance
18 broken,eighths | balance
19 bass-chord,triple | balance
20 balance,hold | alternate,chords
21 major,thumb | together
22 opposite,eighths | together
23 inversions | bass-chord
24 alberti | balance
25 syncopation,bass-chord | chords
26 polyrhythm | triple
27 syncopation,rests | chords
28 canon | rests
29 triple,bass-chord | eighths,balance
30 phrases,balance | broken,syncopation
31 canon | hold
32 canon | ratio
33 canon | read-lh
34 canon,eighths | ratio
35 canon,dotted | rests
36 swing | ratio
37 swing | together
38 swing,syncopation | chords
39 swing | accidentals,balance
40 swing,rests | balance
41 eighths,ratio | pulse
42 triplets | ratio
43 triplets,sixteenths | eighths
44 polyrhythm | ratio
45 sixteenths,triplets | pulse
46 create | pulse
47 create,rests | pulse
48 create | voice-leading,balance
49 create,swing | accidentals
50 create,balance | phrases
51 keyboard | read-rh
52 pulse,durations | keyboard
53 rests | pulse
54 dotted | eighths
55 triple,pulse | durations
56 fingers | read-rh
57 fingers | read-lh
58 read-rh,read-lh | keyboard
59 read-rh,intervals | fingers
60 read-lh | fingers
61 hold | balance
62 ratio | durations
63 hold | bass-chord
64 alternate | rests
65 phrases | hold
66 accidentals | read-rh
67 thumb | major
68 thumb | read-lh,major
69 thumb,accidentals | major
70 thumb,accidentals | major
71 minor,ear | chords
72 chords | minor
73 chords,rests | pulse
74 inversions | chords
75 voice-leading | bass-chord
76 chords,hold | balance
77 bass-chord,ratio | balance
78 chords,ratio | balance
79 broken | balance
80 voice-leading | bass-chord
81 touch | pulse
82 touch | balance
83 pedal | chords
84 triple,bass-chord | balance,phrases
85 reading | phrases
86 pulse,rests | durations
87 shift | fingers
88 shift | read-lh
89 thumb | fingers
90 shift,rests | read-rh
91 major,opposite | thumb
92 major,opposite | accidentals
93 major,thumb | together
94 major,accidentals | thumb
95 shift,triple | phrases,accidentals
96 intervals,read-rh | keyboard
97 intervals,read-lh | keyboard
98 intervals | chords
99 intervals,hold | balance
100 ear,intervals | keyboard
101 minor | thumb
102 minor,accidentals | thumb
103 minor,accidentals | thumb
104 minor,accidentals | thumb
105 minor,voice-leading | chords
106 compound | pulse
107 compound,dotted | phrases
108 sixteenths | pulse
109 dotted,sixteenths | eighths
110 syncopation | ratio
111 chords,minor | ear
112 voice-leading | bass-chord
113 voice-leading,accidentals | major
114 voice-leading,accidentals | major
115 voice-leading | ear
116 seventh | minor
117 seventh,voice-leading | chords
118 sus | ear
119 bass-chord,voice-leading | inversions
120 seventh,sus | balance
121 broken | balance
122 alberti | balance
123 syncopation,bass-chord | balance
124 pedal | voice-leading
125 broken,alternate | eighths
126 major,accidentals | thumb
127 major,accidentals | thumb
128 reading,read-rh | rests
129 reading,read-lh | durations
130 create | voice-leading
131 chords | read-rh
132 chords | read-lh
133 together,chords | durations
134 alternate | chords
135 voice-leading | inversions
136 voice-leading,ratio | chords
137 inversions | chords
138 voice-leading | minor
139 broken | read-rh
140 broken | read-lh
141 broken,together | chords
142 broken,opposite | chords
143 hold,broken | balance
144 hold,broken | alternate
145 ratio | chords
146 eighths,hold | broken
147 bass-chord,alternate | rests
148 bass-chord,triple | chords
149 alberti | balance
150 syncopation | chords
151 balance | hold
152 balance | alternate
153 seventh | voice-leading
154 phrases,balance | broken
155 balance,hold,phrases | chords
156 balance,hold,phrases | alternate,chords
157 alternate,balance,phrases |
158 voice-leading,ratio,phrases | inversions
159 inversions,balance,phrases |
160 minor,voice-leading,phrases | balance
161 broken,balance,phrases |
162 broken,eighths,phrases |
163 opposite,broken,phrases |
164 ratio,hold,phrases |
165 dotted,durations,phrases | minor
166 eighths,accidentals,phrases | balance
167 bass-chord,balance,phrases |
168 triple,bass-chord,phrases | accidentals,balance
169 alberti,balance,phrases |
170 syncopation,balance,phrases | chords
171 seventh,phrases | pedal
172 phrases,balance | hold,broken,alberti,ratio
`,i={};for(const n of o.trim().split(`
`)){const[a,h=""]=n.split("|"),[t,...e]=a.trim().split(/\s+/);i[t]={primary:e.join("").split(","),context:h.trim().split(",").filter(Boolean)}}window.PIANO_SKILLS={version:1,groups:r.map(([n,a,h])=>({id:n,label:a,icon:h})),nodes:s.map(([n,a,h,t,e,c])=>({id:n,label:a,group:h,requires:t,starters:e,description:c})),lessons:i,songs:{"nhat-ky-cua-me":{primary:["phrases","balance"],context:["triple","hold","broken","bass-chord","syncopation"],requires:["triple","hold","broken","balance","phrases"]}}}})();
